authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),


]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='home'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('proba/', mainapp.proba, name='proba'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.products, name='index'),
   path('<int:pk>/', mainapp.products, name='category'),
    ]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class ShopUser(AbstractUser):
    avatar = models.ImageField(verbose_name='аватарка', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

mainapp/models.py
from django.db import models


# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    age = models.PositiveIntegerField(verbose_name='Возраст', default=0)

    def __str__(self):
        return f"{self.name} {self.last_name}"


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название', max_length=80, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=125)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=100, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm
from django.contrib import auth
from django.urls import reverse
from authapp.forms import ShopUserRegisterForm


# Create your views here.
def login(request):
    title = 'вход'
    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('home'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))


def register(request):
    return HttpResponseRedirect(reverse('main'))


def edit(request):
    return HttpResponseRedirect(reverse('main'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)

mainapp/views.py
from django.shortcuts import render
from django.http import HttpRequest
from .models import ProductCategory, Product


# Create your views here.

def main(request):
    # content = {'products': prod}
    main_menu = [
        {'href': 'home', 'name': 'домой'},
        {'href': 'products:index', 'name': 'продукты'},
        {'href': 'contact', 'name': 'контакты'}
    ]

    data = [
        {'title': 'Магазин'},
        {'main_menu': main_menu},

    ]
    products = Product.objects.all()[0:4]

    return render(request, 'mainapp/index.html', {
        'data': data,
        'products': products,
    })


def products(request, pk=None):
    print(pk)
    main_menu = [
        {'href': 'home', 'name': 'домой'},
        {'href': 'products:index', 'name': 'продукты'},
        {'href': 'contact', 'name': 'контакты'}
    ]

    data = [
        {'title': 'Продукты'},
        {'main_menu': main_menu},
    ]
    category = ProductCategory.objects.all()
    return render(request, 'mainapp/products.html', {
        'data': data,
        'category': category,
    })


def contact(request):
    main_menu = [
        {'href': 'home', 'name': 'домой'},
        {'href': 'products:index', 'name': 'продукты'},
        {'href': 'contact', 'name': 'контакты'}
    ]

    data = [
        {'title': 'Контакты'},
        {'main_menu': main_menu},
    ]
    return render(request, 'mainapp/contact.html', {
        'data': data,
    })


def proba(request):
    prod = Product.objects.all()
    content = {'products': prod}
    return render(request, 'mainapp/proba.html', content)

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
	<div class="container">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>

            {% block content %}

            {% endblock %}
        </div>
	</div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}
    <form >

    </form>
    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            зарегистрироваться
        </a>
    </button>
{% endblock %}

mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
{% extends 'mainapp/layout.html' %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ data.0.title }}
        {% endblock %}
    </title>
</head>
<body>
	<div class="container">
     {% block content %}
		<div class="hero">
			{% include 'mainapp/includes/inc_menu.html' %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

		<div class="clr"></div>
	</div>	
{% endblock %}

			
</body>
</html>

mainapp/templates/mainapp/includes/inc_menu.html
<div class="header clearfix">
    <a href="{% url 'home' %}" class="logo"></a>

    <ul class="menu">

        {% for item in data.1.main_menu %}
            <li>
                <a href="{% url item.href %}" {% if request.resolver_match.url_name == item.href %}
                   class="active" {% endif %} >{{ item.name }}</a>
            </li>
        {% endfor %}

        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
              <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
              <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>

    </ul>

    <a href="#" class="search"></a>
</div>

mainapp/templates/mainapp/index.html
<!DOCTYPE html>
{% extends 'mainapp/layout.html' %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
    {% block title %}
       {{ data.0.title|upper }}
    {% endblock %}
    </title>

</head>
<body>

	<div class="container">
    {% block content %}
		<div class="slider">
            {% include 'mainapp/includes/inc_menu.html' %}


			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt="" ></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
                {% for product in products %}
				<div class="block">
					<a href="/products/{{ product.id }}"><img class = "prod-image" src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
{#							<h3>{{ product.category.name }}</h3>#}
							<h4>{{ product.name }}</h4>
                            <p> {{ product.short_desc }}</p>
						</div> 
					</a>
				</div>
                {% endfor %}

{#				<div class="block">#}
{#					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="" >#}
{#						<div class="text">#}
{#							<img src="{% static 'img/icon-hover.png' %}" alt="">#}
{#							<h4>Стул повышенного качества</h4>#}
{#							<p>Не оторваться. </p>#}
{#						</div>#}
{#					</a>#}
				</div>	
			</div>
		</div>


{% endblock %}
</div>

	
</body>
</html>

mainapp/templates/mainapp/layout.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="utf-8">
	<title>
    {% block title %}
         {{ content.title }}
    {% endblock %}
     </title>
    {% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>

	<div class="container">
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
		<div class="clr"></div>
	</div>
{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/proba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    

</head>
<body>
<div>
    <img src="/media/{{ products.0.image }}" alt="">
</div>
</body>
</html>

mainapp/templates/mainapp/products.html
<!DOCTYPE html>
{% extends 'mainapp/layout.html' %}
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ data.0.title }}
        {% endblock %}
    </title>
</head>

<body>

	<div class="container">

     {% block content %}
		<div class="hero-white">
			 {% include 'mainapp/includes/inc_menu.html' %}
		</div>
		<div class="details">
			<div class="links clearfix">
				<ul class="links-menu">
					<li><a href="#" class="active">все</a></li>
					<li><a href="#">дом</a></li>
					<li><a href="#">офис</a></li>
					<li><a href="#">модерн</a></li>
					<li><a href="#">классика</a></li>
				</ul>
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{% static 'img/slider1.jpg' %}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-21.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="{% static 'img/product-31.jpg' %}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>

		<div class="clr"></div>

	</div>	
{% endblock %}


</body>
</html>